site_name: PicImageSearch
site_url: https://pic-image-search.kituin.fun
site_description: >-
  PicImageSearch is an aggregated image search engine for reverse image search.

repo_url: https://github.com/kitUIN/PicImageSearch
repo_name: kitUIN/PicImageSearch
edit_uri: edit/main/docs/

theme:
  name: material
  icon:
    edit: material/pencil
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - navigation.expand
    - navigation.footer
    - navigation.top
  palette:
    - media: (prefers-color-scheme)
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html

nav:
  - Introduction: index.md
  - Docs:
    - Engines:
        - AnimeTrace: engines/anime-trace.md
        - Ascii2D: engines/ascii2d.md
        - Baidu: engines/baidu.md
        - Bing: engines/bing.md
        - Copyseeker: engines/copyseeker.md
        - EHentai: engines/ehentai.md
        - Google: engines/google.md
        - GoogleLens: engines/google-lens.md
        - IQDB: engines/iqdb.md
        - Lenso: engines/lenso.md
        - SauceNAO: engines/saucenao.md
        - Tineye: engines/tineye.md
        - TraceMoe: engines/tracemoe.md
        - Yandex: engines/yandex.md
    - Model:
        - AnimeTrace: model/anime-trace.md
        - Ascii2D: model/ascii2d.md
        - Baidu: model/baidu.md
        - Bing: model/bing.md
        - Copyseeker: model/copyseeker.md
        - EHentai: model/ehentai.md
        - Google: model/google.md
        - GoogleLens: model/google-lens.md
        - IQDB: model/iqdb.md
        - Lenso: model/lenso.md
        - SauceNAO: model/saucenao.md
        - Tineye: model/tineye.md
        - TraceMoe: model/tracemoe.md
        - Yandex: model/yandex.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_category_heading: true
            show_if_no_docstring: true
            show_root_heading: false
            show_source: true
          paths: [.]
  - i18n:
      docs_structure: folder
      languages:
        - name: English
          locale: en
          build: true
          default: true
        - name: 简体中文
          locale: zh
          build: true
          nav_translations:
            Introduction: 介绍
            Docs: 文档
        - name: Русский
          locale: ru
          build: true
          nav_translations:
            Introduction: Введение
            Docs: Документация
        - name: 日本語
          locale: ja
          build: true
          nav_translations:
            Introduction: 紹介
            Docs: ドキュメント

watch:
  - PicImageSearch
