"""
This type stub file was generated by pyright.
"""

from html5lib.treebuilders import _base

"""
Legacy module - don't use in new code!

html5lib now has its own proper implementation.

This module implements a tree builder for html5lib that generates lxml
html element trees.  This module uses camelCase as it follows the
html5lib style guide.
"""
class DocumentType:
    def __init__(self, name, publicId, systemId) -> None:
        ...
    


class Document:
    def __init__(self) -> None:
        ...
    
    def appendChild(self, element): # -> None:
        ...
    


class TreeBuilder(_base.TreeBuilder):
    documentClass = Document
    doctypeClass = DocumentType
    elementClass = ...
    commentClass = ...
    fragmentClass = Document
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def reset(self): # -> None:
        ...
    
    def getDocument(self): # -> None:
        ...
    
    def getFragment(self): # -> list[Any]:
        ...
    
    def insertDoctype(self, name, publicId, systemId): # -> None:
        ...
    
    def insertComment(self, data, parent=...): # -> None:
        ...
    
    def insertRoot(self, name): # -> None:
        ...
    


