"""
This type stub file was generated by pyright.
"""

from lxml_html_clean import *

"""Backward-compatibility module for lxml_html_clean"""
__all__ = ["clean_html", "clean", "Cleaner", "autolink", "autolink_html", "word_break", "word_break_html"]
