name: Close stale issues

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  issues: write

jobs:
  close_stale_issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days."
          close-issue-message: "This issue was closed because it has been stalled for 5 days with no activity."
          days-before-issue-stale: 30
          days-before-issue-close: 5
          exempt-issue-labels: "bug,pinned"
