name: Linter

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruff
        uses: astral-sh/ruff-action@v3

      - name: Run Ruff format
        run: ruff format --diff

      - name: Run Ruff check
        run: ruff check --diff
